### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by teto**
I've started working on the doc when my brain asked for grunt work. will resume next time that happens (very soon then xD). How did you generate the banner/header for neomake ?

### CODE REVIEW

**Comment by blueyed** [comment]
Nice!

> How did you generate the banner/header for neomake ?

https://github.com/neomake/neomake/issues/690

**Comment by teto** [comment]
I use winhl directly so closing.

**Comment by blueyed** [comment]
Me too, but let's keep this open for when I update this plugin - the plan/idea is to make it also wrap winhl.

**Comment by teto** [comment]
cleanibg up my backlog

**Pull request closed without merging**
